### ISSUE TITLE
Text doesn't seem to show up in Firefox 35.0

### ISSUE THREAD

**Issue by lewiscowper** [arnemart/furious.ly#1]
![screen shot 2015-01-21 at 14 56 09](https://cloud.githubusercontent.com/assets/593574/5838239/e1b5f6bc-a17d-11e4-850d-b7714fc7fc5f.png)

As shown, I want to have a look into how the HTML is being generated, and I'll try and debug it for myself.

It's working fine in Chrome 39, and it's really cool. Thanks for sharing!

**Comment by arnemart** [comment]
Thanks for the bug report! Firefox doesn't like `innerText`. Should have tested it I guess, I’ll fix it shortly :-)
